services:
  - type: web
    name: pdf-translator-api
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr tesseract-ocr-khm
      pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6